version: '3'

services:
  book_catalog:
    build: ./book_catalog
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://deelaka:a8cWwVwOcgbgSE0j2L9HCeGCxc09Pxpn@dpg-cs158qa3esus739aq0i0-a.oregon-postgres.render.com/db92d
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  inventory_management:
    build: ./inventory_management
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://deelaka:a8cWwVwOcgbgSE0j2L9HCeGCxc09Pxpn@dpg-cs158qa3esus739aq0i0-a.oregon-postgres.render.com/db92d
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
